name: Nuget Release

on: workflow_dispatch
  
jobs:
  deploy:
    uses: koliva8245/github.workflows/.github/workflows/nuget-release.yml@main
    with:
      artificats-workflow: build.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      nuget-api-token: ${{ secrets.NUGET_API_TOKEN }}
